server:
  port: 80
eureka:
  client:
    serviceUrl:
       defaultZone: http://eureka7001:7001/eureka/,http://eureka7003:7003/eureka/

feign:
  hystrix:
    enabled: true
spring:
  application:
    name: spring-cloud-feign

